/*
 * generated by Xtext
 */
package org.idsl.language;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IdslRuntimeModule extends org.idsl.language.AbstractIdslRuntimeModule {

}
