/*
* generated by Xtext
*/
package org.idsl.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IdslStandaloneSetup extends IdslStandaloneSetupGenerated{

	public static void doSetup() {
		new IdslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

