/*
 * generated by Xtext
 */
package org.idsl.language.validation
//import org.eclipse.xtext.validation.Check

import java.util.ArrayList
import java.util.Collections
import java.util.HashSet
import java.util.List
import java.util.Set
import org.eclipse.xtext.validation.Check
import org.idsl.language.generator.IdslConfiguration
import org.idsl.language.generator.IdslGeneratorDesignSpace
import org.idsl.language.generator.IdslGeneratorExpression
import org.idsl.language.idsl.AltProcessModel
import org.idsl.language.idsl.AtomicProcessModel
import org.idsl.language.idsl.AtomicResourceTree
import org.idsl.language.idsl.BExp
import org.idsl.language.idsl.BExpArithmetic
import org.idsl.language.idsl.BExpBi
import org.idsl.language.idsl.BExpCmpString
import org.idsl.language.idsl.BExpDspace
import org.idsl.language.idsl.BExpFalse
import org.idsl.language.idsl.BExpNeg
import org.idsl.language.idsl.BExpString
import org.idsl.language.idsl.BExpTrue
import org.idsl.language.idsl.BExpValue
import org.idsl.language.idsl.BExpconstraint
import org.idsl.language.idsl.CompoundResourceTree
import org.idsl.language.idsl.DesAltProcessModel
import org.idsl.language.idsl.DesignSpaceModel
import org.idsl.language.idsl.DesignSpaceParam
import org.idsl.language.idsl.ExtendedProcessModel
import org.idsl.language.idsl.IdslPackage
import org.idsl.language.idsl.MVExpECDFbasedonDSI
import org.idsl.language.idsl.Mapping
import org.idsl.language.idsl.Measurement
import org.idsl.language.idsl.MeasurementPTAModelChecking
import org.idsl.language.idsl.MeasurementPTAModelChecking2
import org.idsl.language.idsl.MeasurementSimulation
import org.idsl.language.idsl.MeasurementSimulationINT
import org.idsl.language.idsl.MeasurementTheoBounds
import org.idsl.language.idsl.Model
import org.idsl.language.idsl.MutexProcessModel
import org.idsl.language.idsl.PaltProcessModel
import org.idsl.language.idsl.ParProcessModel
import org.idsl.language.idsl.ProcessModel
import org.idsl.language.idsl.ResourceModel
import org.idsl.language.idsl.ResourceSchedulingPolicy
import org.idsl.language.idsl.ResourceTree
import org.idsl.language.idsl.Scenario
import org.idsl.language.idsl.SchedulingPolicy
import org.idsl.language.idsl.SchedulingPolicyFIFO
import org.idsl.language.idsl.SchedulingPolicyNonDet
import org.idsl.language.idsl.SeqParProcessModel
import org.idsl.language.idsl.SeqProcessModel
import org.idsl.language.idsl.Service
import org.idsl.language.idsl.TimeSlice
import org.idsl.language.idsl.UExp
import org.idsl.language.idsl.UExpAggregatedMeasurement
import org.idsl.language.idsl.UExpExpr
import org.idsl.language.idsl.UExpFuncLowerBound
import org.idsl.language.idsl.UExpFuncServiceRequest
import org.idsl.language.idsl.UExpFuncUpperBound
import org.idsl.language.idsl.UExpFuncUtilization
import org.idsl.language.idsl.UExpParameterInt
import org.idsl.language.idsl.UExpParameterTrueIntRange
import org.idsl.language.idsl.MVExpExponential
import org.idsl.language.idsl.TimeScheduleCDF
import org.idsl.language.idsl.MVExpECDFfromfile
import org.idsl.language.idsl.MVExpECDFProduct
import org.idsl.language.idsl.MVExpECDFabstract
import org.idsl.language.idsl.LoadBalancerProcessModel
import org.idsl.language.idsl.TaskLoad
import org.idsl.language.idsl.Exp
import org.eclipse.xtend.expression.Resource
import org.eclipse.emf.ecore.EStructuralFeature

// Make sure that only PAR processes have a MVExp
// Check SeqPar for equal lenghts/
// Check DSMs for providing enough support for dspaces in scenario

class IdslValidator extends AbstractIdslValidator {
	var boolean showInfo 	= false
	var boolean showWarning = false
	
	def info2(String message, EStructuralFeature feature){
		if(showInfo)
			info(message,feature)
	}

	def warning2(String message, EStructuralFeature feature){
		if(showWarning)
			warning(message,feature)
	}
	
	@Check
	def make_sure_printGenerator_is_of_type_eCDF_only (TimeScheduleCDF cdf){
		switch(cdf.ecdf.head){
			MVExpECDFfromfile:   error("Generator: MVExpECDFfromfile not supported yet", null)
			MVExpECDFProduct:    error("Generator: MVExpECDFProduct not supported yet", null)
			MVExpECDFabstract:   error("Generator: MVExpECDFabstract not supported yet", null)
			MVExpECDFbasedonDSI: error("Generator: MVExpECDFbasedonDSI not supported yet", null)
		}
	}
	
	@Check
	def palt_must_have_at_least_two_alternatives (PaltProcessModel pm){
		if(IdslConfiguration.Lookup_value("palt_may_have_one_alternative")!="yes")		
			if(pm.ppmodel.length<2)
				error("PALT process must contain at least two alteratives",null)
	}

	@Check
	def alt_must_have_at_least_two_alternatives (AltProcessModel pm){
		if(IdslConfiguration.Lookup_value("alt_may_have_one_alternative")!="yes")
			if(pm.pmodel.length<2)
				error("ALT process must contain at least two alteratives",null)
	}

	@Check
	def lbalt_must_have_at_least_two_alternatives (LoadBalancerProcessModel pm){
		if(IdslConfiguration.Lookup_value("lbalt_may_have_one_alternative")!="yes")
			if(pm.pmodel.length<2)
				error("Load balancer process must contain at least two alteratives",null)
	}
	
	@Check
	def warn_that_multiple_policies_require_an_lbpolicy_in_the_design_space (LoadBalancerProcessModel pm){
		if(pm.lb_policies.length>1)
		warning2("Two or more policies have been defined. The design space is impicetely augmented with \"lb_policy_....\" to select each policy in seperate designs.",null)
	}
	
	@Check
	def either_BExpFileWhitelist_in_DesignSpace_or_DSparams(DesignSpaceModel dsm){
		if(!dsm.bexpwhitelist.empty && !dsm.dsparam.empty) // both the whitelist and dsparams are defined, raise an error
			error("Design space is duplicatly defined via a whitelist AND dsparams, remove one definition", null)
		
		if(dsm.bexpwhitelist.empty && dsm.dsparam.empty) // neithor the whitelist nor dsparams are defined, raise an error
			error("Design space is neither defined via a whitelist nor dsparams, add one definition", null)
	}

	/*@Check
	def warn_that_only_one_instance_is_measured(MeasurementSimulationINT measure){
		if(measure.ospi.length==0)
			warning2("Only one instance will be measured. Add OneStopwatchPerInstance to measure all instances.",null)		
	} */
	
	/*@Check
	def warn_that_only_one_instance_is_measured(MeasurementSimulation measure){
		if(measure.ospi.length==0)
			warning2("Only one instance will be measured. Add OneStopwatchPerInstance to measure all instances.",null)		
	}*/
	
	@Check // no _ in order to make parsing possible
	def no_underscore_in_designspace_param (DesignSpaceParam dsp){
		if(dsp.variable.contains("_"))
			error("Design space variable may not contain _ character", null)
		if(dsp.value.contains("_"))
			error("Design space value may not contain _ character", null)
	}
	
	@Check // if scenario contains duplicate services. They lead to duplicate code in modest.
	def no_duplicate_servicerequests_in_a_scenario (Scenario scenario){
		// just for testing: scenario.ainstance.head.activity_id.head.name
		
		var serv_names = new ArrayList<String>
		for(serv_req:scenario.ainstance){
			val new_serv = serv_req.activity_id.head.name
			if (serv_names.contains(new_serv)) 
				error("Scenario "+new_serv+" is multiply defined!", null)
			serv_names.add(new_serv)
		}
	}
	
	@Check
	def valid_model_selected (MeasurementPTAModelChecking measurepta){
		val num_models = new Integer(IdslConfiguration.Lookup_value("number_of_simplified_models_with_nondeterministic_segments"))
		var segments = measurepta.num_segments
		if(segments!=null && !segments.empty){		
			if (segments.head>Math.pow(2,num_models as double))
				error ("selected number of segments is greater than in the generated models. Lower the amount of segments or increase the number of generated models",null)
			if ((Math.log(segments.head as double)/Math.log(2.0))%1!=0)
				error ("Number of segments needs to be a power of 2.", null)		
		}
	}

	@Check
	def check_uniqueness_and_nonemptyness_of_MVExpECDFbasedonDSI_selects(MVExpECDFbasedonDSI ecdf_dsi){
		var select_set = new HashSet<String>
		var size = ecdf_dsi.select_ecdfs.length
		
		for(select_cdf:ecdf_dsi.select_ecdfs){
			if(select_cdf.select.empty || select_cdf.select.head=="")
				error("At least one entry of MVExpECDFbasedonDSI is empty",null)
			select_set.add(select_cdf.select.head)
		}
		
		if(select_set.size<size) // duplicates present
			error("The entries of MVExpECDFbasedonDSI are not unique",null)
	}
	

	
	@Check
	def check_uniqueness_and_nonemptyness_of_DesAltProcessModel_selects(DesAltProcessModel desalt_pm){
		var select_set = new HashSet<String>
		var size = desalt_pm.pmodel.length
		
		for(select_cdf:desalt_pm.pmodel){
			if(select_cdf.select.empty || select_cdf.select.head=="")
				error("At least one entry of DesAltProcessModel is empty",null)
			select_set.add(select_cdf.select.head)
		}
		
		if(select_set.size<size) // duplicates present
			error("The entries of DesAltProcessModel are not unique",null)	
	}
	
	
	@Check
	def check_number_of_entries_of_desalt (Model model){
		var desalts = model.eAllContents.toIterable.filter(typeof(DesAltProcessModel)).toList 
		var dsms = model.eAllContents.toIterable.filter(typeof(DesignSpaceModel)).toList
				
		for (desalt:desalts)
			for(dsm:dsms)
				if (desalt.pmodel.length!=IdslGeneratorDesignSpace.DSM_number_of_entries_for_param(dsm,desalt.param.head))
					warning2("The number of entries of DesAlt with parameter "+desalt.param.head+" does not match the size of the Design Space Model",null)
	}
	
	@Check 
	def count_dspaces (Model model){ // If exponentials are used, simulation should be the only Measure
		var aexpexponential_size = model.eAllContents.toIterable.filter(typeof(MVExpExponential)).toList.length
		var measures			 = model.eAllContents.toIterable.filter(typeof(Measurement)).toList
		
		for(measure:measures){
			switch(measure){
				MeasurementSimulationINT: if(false) error("",null) // do nothing
				MeasurementSimulation:	  if(false) error("",null) // do nothing
				default: 				  if(aexpexponential_size>0)
											warning2("Exponentials can be complex when used with measured other than simulation", null)
			}			
		}
	}
	
	@Check 
	def warn_for_design_space_with_one_element (DesignSpaceModel dsm){
		var int elems = 1
		for(ds_param:dsm.dsparam)
			elems = elems * ds_param.value.length
		if(elems==1)
			warning2("The design space has only 1 instance!",null)
	}
	
	@Check 
	def more_than_one_scenario_in_model (Model model){
		if (model.scenario.length>2) // multiple scenarios
			warning2("iDSL might not support multiple scenarios", null)
	}
	
	@Check
	def check_number_of_entries_of_MVExpECDFbasedonDSI (Model model){
		var dspaceECDFs = model.eAllContents.toIterable.filter(typeof(MVExpECDFbasedonDSI)).toList 
		var dsms = model.eAllContents.toIterable.filter(typeof(DesignSpaceModel)).toList
		
		for (dspaceECDF:dspaceECDFs)
			for(dsm:dsms)
				if(dspaceECDF.select_ecdfs.length!=IdslGeneratorDesignSpace.DSM_number_of_entries_for_param(dsm,dspaceECDF.param.head)
				)
					warning2("The number of entries of dspaceECDF with parameter "+dspaceECDF.param.head+" does not match the size of the Design Space Model",null)
	}	
	
	def List<String> params_of_DSM(DesignSpaceModel dsm){ // Returns all the parameters of a DesignSpaceModel
		var param_lst = new ArrayList<String>
		for(dsparam:dsm.dsparam)
			param_lst.add(dsparam.variable.head)
		return param_lst
	}
	
	@Check
	def check_if_DSM_contains_desalt_parameter (Model model){
		var desalts = model.eAllContents.toIterable.filter(typeof(DesAltProcessModel)).toList 
		var dsms = model.eAllContents.toIterable.filter(typeof(DesignSpaceModel)).toList
		
		for (desalt:desalts)
			for (dsm:dsms){
				if (!dsm.bexpwhitelist.empty)
					warning2("Whitelist from CSV file defined. No checking for dependencies regarding desalts and dspaces.",null)
				else
				if(!params_of_DSM(dsm).contains(desalt.param.head))
					error("DesAltProcessModel has parameter "+desalt.param.head+", which is not part of the DesignSpaceModel",null)	
			}
	}
	
	@Check
	def check_if_DSM_contains_MVExpECDFbasedonDSI_parameter (Model model){
		var ecdfs_based_on_dsi = model.eAllContents.toIterable.filter(typeof(MVExpECDFbasedonDSI)).toList 
		var dsms = model.eAllContents.toIterable.filter(typeof(DesignSpaceModel)).toList
		
		for (ecdf:ecdfs_based_on_dsi)
			for (dsm:dsms)
				if(!params_of_DSM(dsm).contains(ecdf.param.head))
					error("MVExpECDFbasedonDSI has parameter "+ecdf.param.head+", which is not part of the DesignSpaceModel",null)
	}

	@Check // Each process of the processModel exactly once in the mapping
	def each_process_once_in_the_mapping_of_service (Service service){
		var Set<String> atomic_procs 		= list_of_atomicprocess_names(service.extprocess_id).toSet
		var Set<String> procs 				= list_of_names(service.extprocess_id).toSet
		var Set<String> procs_in_map 		= new HashSet<String>
		
		for(proc_res:service.mapping.head.prassignment)
				procs_in_map.add(proc_res.process)
		
		var Set<String> undefined   = new HashSet<String> (atomic_procs)
		undefined.removeAll(procs_in_map)
		
		// TODO: IDEALLY YOU CHECK WHETHER THE PROCESS TREE COMPLETELY CONNECTS TO A MAPPING
		//if(undefined.size>0)
		//	warning2("Atomic processes "+undefined.toString+" are part of the process, but not defined in the mapping.",null)		
		
		var Set<String> overdefined = new HashSet<String> (procs_in_map)
		overdefined.removeAll(procs)
		if(overdefined.size>0)
			warning2("Processes "+overdefined.toString+" are defined in the mapping, but are not part of the process.",null)
	}
	
	@Check // Check for double, unambiqously defined processes in the mapping
	def each_process_in_mapping_unique(Mapping mapping){
		var Set<String> amb_procs = new HashSet<String>
		var prs = mapping.prassignment
		for(pr1:prs)
			for(pr2:prs)
				if(pr1.process==pr2.process && pr1.resource!=pr2.resource) // ambiguity/contradiction
					amb_procs.add(pr1.process)
					
		if (amb_procs.length>0)
			error("Processes "+amb_procs.toString+" are ambigously defined.",null)
	}
	
	@Check // Check whether for each resources all scheduling policies and time slicings are the same
	def equal_scheduling_policies_and_time_slices_per_resource(Model model){
		var serv_list = model.amodel
		var sched_policies = schedule_policies_per_system(serv_list)
		
		// compare scheduling policies in a 2D fashion
		for(sched_pol1:sched_policies)for(sched_pol2:sched_policies)
			compare_res_sched_policies(sched_pol1, sched_pol2)
	}
	
	def schedule_policies_per_system(List<Service> service_list){
		var List<ResourceSchedulingPolicy> schedpol_list = new ArrayList<ResourceSchedulingPolicy>
		for(serv:service_list)
			schedpol_list.addAll(serv.mapping.head.rspolicy)	
		return schedpol_list
	}
	
	def compare_res_sched_policies(ResourceSchedulingPolicy sched_pol1, ResourceSchedulingPolicy sched_pol2){
		if (sched_pol1.resource==sched_pol2.resource){ 
			if (IdslConfiguration.Lookup_value("Debug_mode")=="true"){
				System.out.println(sched_pol1.resource+" AND "+sched_pol1.resource)
				System.out.println(sched_pol1.policy.toString+" AND "+sched_pol1.policy.toString)
				System.out.println(sched_pol1.timeslice.toString+" AND "+sched_pol1.timeslice.toString)
			}
			
			if (!compare_sched_policy(sched_pol1.policy, sched_pol2.policy))
				error("Scheduling policy of resource "+sched_pol1.resource+" is defined ambiguously",null)
			if (!compare_time_slice(sched_pol1.timeslice, sched_pol2.timeslice))
				error("Time slicing of resource "+sched_pol1.resource+" is defined ambiguously",null)
		}
	}
	
	def boolean compare_sched_policy(SchedulingPolicy s1, SchedulingPolicy s2){
		switch(s1){
			SchedulingPolicyNonDet: switch(s2){ SchedulingPolicyNonDet: return true  default: return false}
			SchedulingPolicyFIFO:	switch(s2){ SchedulingPolicyFIFO:	return true  default: return false}
			default: return false
		}
	}
	
	def boolean compare_time_slice(TimeSlice t1, TimeSlice t2){
		var time1=t1.time
		var time2=t2.time
		
		// one of the values is null (non-preemption)
		if (time1==null && time2==null ) return true   		// both null
		else if (time1==null || time2==null ) return false  // one null		
		return IdslGeneratorExpression.equalsAExp(time1, time2)
	}

	@Check
	def seqpar_pars_have_equal_length(SeqParProcessModel spm){
		var par_length = spm.pmodel.head.pmodel.length // length of first par

		for(par:spm.pmodel){ // see if others match the length of first par
			if (par.pmodel.length!=par_length)
				error("Pars of the SeqPar are of different lengths",null)	
		}
	}

	@Check
	def duplicateMeasures (Model model){
		for(measure1:model.experiment){
			var cnt=0
			for(measure2:model.experiment) if(measure1.class==measure2.class) cnt = cnt +1 
			if(cnt>1) 
				error("Multiple measurements of kind "+measure1.class.toString+" found.", IdslPackage::eINSTANCE.model_Experiment)
		}
	}
	
	@Check
	def check_if_model_checking_pta2_is_the_only_measurement_when_defined (Model model){
		var num_experiments = model.experiment.length
		if(num_experiments>1){ // potential conflict
			for(measurement:model.experiment) 
				switch(measurement) { MeasurementPTAModelChecking2: error("Measure model checking PTA2 is defined besides other measurements, leading to potential conflicts in the design space with modeltimeunit and segments", null) }
		}	
	}
	
	@Check
	def check_if_simulation_real_and_simulation_int_coincide (Model model){
		var sim_real_count = 0
		var sim_int_count  = 0
		for(measurement:model.experiment) 
			switch(measurement) { 
				MeasurementSimulation: 		sim_real_count = sim_real_count + 1
				MeasurementSimulationINT:	sim_int_count  = sim_int_count + 1	
			}	
		if(sim_real_count>0 && sim_int_count>0)
			error("Measure simulation real and measure simulation int may not coincide",null)
	}

	@Check
	def infoWhenNoMeasures (Model model){
		var measurements = model.eAllContents.toIterable.filter(typeof(Measurement)).toList
		if(measurements.empty)
			info2("No measurements defined. Only non-performance artifacts can be retrieved", null)	
	}
	 	
	@Check // whether some design variables are used, which are not part of the design space
	def  DesignSpaceVariablesUsedAndCovered ( Model model ){
		for(scenario:model.scenario)
			for(ds:model.study.head.substudy.head.dspacem){
			var varsUsed	= IdslGeneratorDesignSpace.DesignSpaceVariablesUsed(scenario)
			var varsCovered = IdslGeneratorDesignSpace.DesignSpaceVariablesCovered(ds)
			varsUsed.removeAll(varsCovered)
			if (varsUsed.length>0){
				error("DesignSpace does not support the following variables"+varsUsed.toString,null)
			}	
		}
	}
	
	@Check // which dpsace variables are covered
	def checkDspacesDefined(DesignSpaceModel dsm){
		var Set<String> dsvars=new HashSet
		dsvars.addAll(IdslGeneratorDesignSpace.DesignSpaceVariablesCovered(dsm))
		if (dsvars.length>0)
			info2 ("DesignSpace supports the following variables"+dsvars.toString,null)	
	}

	@Check // which dspace variables are used
	def checkDSpacesUsed (Scenario s){ // determines which dspaces are used in a scenario
		var Set<String> dsvars=new HashSet
		dsvars.addAll(IdslGeneratorDesignSpace.DesignSpaceVariablesUsed(s))
		if (dsvars.length>0)
			info2 ("Scenario "+s.name.head+" relies on the following DesignSpace variables: "+dsvars.toString,null)
	}	
	
	@Check // whether all the names used in a scenario are unique
	def checkUniqueItems (Scenario s){ // 
		if(IdslConfiguration.Lookup_value("check_for_double_names")=="false") return // quit checking 
		
		var List<String> merge_list = list_of_names(s)
		var Set<String> merge_set = new HashSet(merge_list)
		var Set<String> duplicate_set = new HashSet() // to be filled with duplicate variable names

		System.out.println("Scenario"+s.toString+" "+merge_list.toString) // for debugging

		for(elem:merge_set)
			if (Collections.frequency(merge_list, elem)>1) // found a duplicate
				duplicate_set.add(elem)
		
		if (duplicate_set.length>0)
			error("Scenario" +s.name.head+ " contains the following multiply used variable names: "+duplicate_set.toString,null)
		else
			info2("Scenario" +s.name.head+ " does not contain duplicate variable names",null)	 			
	}

	
	@Check // checks whether the names used in a service are unique
	def checkUniqueItems (Service s){ 
		if(IdslConfiguration.Lookup_value("check_for_double_names")=="false") return // skip checking
	
		var List<String> merge_list = list_of_names(s)
		var Set<String> merge_set = new HashSet(merge_list)
		var Set<String> duplicate_set = new HashSet() // to be filled with duplicate variable names

		System.out.println("Service"+s.toString+" "+merge_list.toString) // for debugging

		for(elem:merge_set)
			if (Collections.frequency(merge_list, elem)>1) // found a duplicate
				duplicate_set.add(elem)
		
		if (duplicate_set.length==0)
			info2("Service" +s.name+ " does not contain duplicate variable names",null)	 
		else
			error("Service "+s.name+" contains the following multiply used variable names: "+duplicate_set.toString,null)		
	}

	def List<String> list_of_names(Scenario s){
		var List<String> ret_list = new ArrayList()
		var Set<ResourceModel> resources = new HashSet() // resource model may overlap
		for(serv:s.ainstance){
			ret_list.addAll(list_of_names(serv.activity_id.head.extprocess_id))
			resources.add(serv.activity_id.head.resource_id)
		}
		for(res:resources)
			ret_list.addAll(list_of_names(res))
		
		//System.out.println("Scenario"+s.toString+" "+ret_list.toString) // for debugging
		return ret_list
	}

	def List<String> list_of_names(Service s){
		var List<String> ret_list = new ArrayList()	
		ret_list.addAll(list_of_names(s.extprocess_id))
		ret_list.addAll(list_of_names(s.resource_id))
		return ret_list	
	}
	
	def List<String> list_of_atomicprocess_names(ExtendedProcessModel epm){
		var List<String> ret_list = new ArrayList()
		ret_list.addAll(list_of_atomicprocess_names(epm.pmodel.head))
		for(el:epm.spm)
			ret_list.addAll(list_of_atomicprocess_names(el.pmodel.head))
		return ret_list			
	}
	
	def List<String> list_of_atomicprocess_names(ProcessModel pm){
		var List<String> ret_list = new ArrayList()
		switch(pm) { AtomicProcessModel:   if(pm.name!=null) ret_list.add(pm.name) } 
	
		switch(pm){ // recursively adds the subprocesses
 			ParProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_atomicprocess_names(el))
			AltProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_atomicprocess_names(el))
			SeqProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_atomicprocess_names(el))
			PaltProcessModel:				for(el:pm.ppmodel) ret_list.addAll(list_of_atomicprocess_names(el.pmodel.head))
			MutexProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_atomicprocess_names(el))
			SeqParProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_atomicprocess_names(el))	
			LoadBalancerProcessModel:		for(el:pm.pmodel) ret_list.addAll(list_of_atomicprocess_names(el))			
		}
		return ret_list		
	}
	
	def boolean contains_load_balancer (ProcessModel pm){
		switch(pm){ // recursive function
 			ParProcessModel:				for(el:pm.pmodel)  if(contains_load_balancer(el)) return true
			AltProcessModel:				for(el:pm.pmodel)  if(contains_load_balancer(el)) return true
			SeqProcessModel:				for(el:pm.pmodel)  if(contains_load_balancer(el)) return true
			PaltProcessModel:				for(el:pm.ppmodel) if(contains_load_balancer(el.pmodel.head)) return true
			MutexProcessModel:				for(el:pm.pmodel)  if(contains_load_balancer(el)) return true
			SeqParProcessModel:				for(el:pm.pmodel)  if(contains_load_balancer(el)) return true	
			LoadBalancerProcessModel:		for(el:pm.pmodel)  return true			
		}
		return false		
	}

	def List<String> list_of_names(ExtendedProcessModel epm){
		var List<String> ret_list = new ArrayList
		ret_list.addAll(list_of_names(epm.pmodel.head))
		for(el:epm.spm)
			//ret_list.add(el.name.head) // do not add, because it leads to duplicates with AbstractionProcessModel
			ret_list.addAll(list_of_names(el.pmodel.head))
		return ret_list	
	}

	def List<String> list_of_names(ProcessModel pm){
		var List<String> ret_list = new ArrayList()
		switch(pm){ // add the names of the processes
			//AbstractionProcessModel:		if(pm.name!=null) ret_list.add(pm.name)     // more than 1 call to the same subprocess is allowed
			AtomicProcessModel:				if(pm.name!=null) ret_list.add(pm.name) 	// more than 1 call to a specific piece of hardware is allowed
 			ParProcessModel:				if(pm.name!=null) ret_list.add(pm.name)
			AltProcessModel:				if(pm.name!=null) ret_list.add(pm.name)
			SeqProcessModel:				if(pm.name!=null) ret_list.add(pm.name)
			PaltProcessModel:				if(pm.name!=null) ret_list.add(pm.name)
			MutexProcessModel:				if(pm.name!=null) ret_list.add(pm.name)
			SeqParProcessModel:				if(pm.name!=null) ret_list.add(pm.name)
			LoadBalancerProcessModel:		if(pm.name!=null) ret_list.add(pm.name)	
		}
		switch(pm){ // recursively adds the subprocesses
 			ParProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_names(el))
 			LoadBalancerProcessModel:		for(el:pm.pmodel) ret_list.addAll(list_of_names(el))
			AltProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_names(el))
			SeqProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_names(el))
			PaltProcessModel:				for(el:pm.ppmodel) ret_list.addAll(list_of_names(el.pmodel.head))
			MutexProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_names(el))
			SeqParProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_names(el))
			DesAltProcessModel:				for(el:pm.pmodel) ret_list.addAll(list_of_names(el.pmodel.head)) 				
		}
		//System.out.println("PM  "+pm.toString+" "+ret_list.toString) // for debugging
		return ret_list
	}

	def List<String> list_of_names(ResourceModel rm){ 
		var List<String> ret_list = new ArrayList()
		ret_list.addAll(list_of_names(rm.restree.head))
		return ret_list	
	}
	
	def List<String> list_of_names(ResourceTree rt){
		var List<String> ret_list = new ArrayList()
		switch(rt){
			AtomicResourceTree:   ret_list.add(rt.name)
			CompoundResourceTree: if(rt.name!=null) ret_list.add(rt.name)
		}
		switch(rt){ CompoundResourceTree: for(sub_rt:rt.rtree) ret_list.addAll(list_of_names(sub_rt)) } // recursion
		return ret_list
	}
	
	// **************** Check wheter the references that are used in utility functions are valid
	@Check
	def validUtilityReference (Model model){
		var measurements = model.experiment
		var utils = model.result.head.utils
		var services = model.amodel

		for(util:utils)
			validUtilityReference(util.util_func, measurements, services)
	}
	
	def void validUtilityReference (UExp uexp, List<Measurement> measurements, List<Service> services){
		switch (uexp){
			UExpExpr: 					{ validUtilityReference(uexp.a1.head, measurements, services) 
										  validUtilityReference(uexp.a2.head, measurements, services)}
			UExpAggregatedMeasurement:  validUtilityReference(uexp.measure.head, measurements, services)
			UExpFuncServiceRequest: 	validUtilityReference(uexp, measurements, services)
			UExpFuncUpperBound:			validUtilityReference(uexp, measurements, services)
			UExpFuncLowerBound:			validUtilityReference(uexp, measurements, services)
			UExpFuncUtilization:		validUtilityReference(uexp, measurements, services)
		}
	}

	def void validUtilityReference (UExpFuncServiceRequest uexp_fsr, List<Measurement> measurements, List<Service> services){
		if (!serviceStringInServiceList (uexp_fsr.service.str, services)) 	error ("Service "+uexp_fsr.service.str+" is not defined", null)
		if (!measurementSimulationInMeasurements(measurements)) 			error ("Latency is used, but no MeasurementSimulationInMeasurements measure defined",null)	
		
		var runs=uexp_fsr.runs
		switch(runs){
			UExpParameterInt: 			if (runs.int12>measurementSimulationRuns(measurements))		error ("The latency queries runs with too high numbers",null)
			UExpParameterTrueIntRange:  if (runs.int2>measurementSimulationRuns(measurements))		error ("The latency queries runs with too high numbers",null)
		}
		
		var reqno=uexp_fsr.requestno
		switch(reqno){
			UExpParameterInt: 			if (reqno.int12>measurementSimulationRequests(measurements))	error("The latency queries requests with too high numbers",null)	
			UExpParameterTrueIntRange:  if (reqno.int2>measurementSimulationRequests(measurements))		error("The latency queries requests with too high numbers",null)
		}
	}

	def void validUtilityReference (UExpFuncUpperBound uexp_fub, List<Measurement> measurements, List<Service> services){
		if (!serviceStringInServiceList (uexp_fub.service.str, services))	error ("Service "+uexp_fub.service.str+" is not defined", null)
		if (!measurementTheoBoundsInMeasurements(measurements))				error ("Upper bound is used, but no TheoBoundsInMeasurements measure defined",null)			
	}

	def void validUtilityReference (UExpFuncLowerBound uexp_flb, List<Measurement> measurements, List<Service> services){
		if (!serviceStringInServiceList (uexp_flb.service.str, services))	error ("Service "+uexp_flb.service.str+" is not defined", null)			
		if (!measurementTheoBoundsInMeasurements(measurements))				error ("Lower bound is used, but no TheoBoundsInMeasurements measure defined",null)			
	}

	def void validUtilityReference (UExpFuncUtilization uexp_fu, List<Measurement> measurements, List<Service> services){
		if (!measurementSimulationInMeasurements(measurements))				error ("Utility is used, but no MeasurementSimulationInMeasurements measure defined",null)
		// DISABLED!!! because it does not work right:  if(!resourceStringInServiceList(uexp_fu.resource.str,services))		error ("Resource "+uexp_fu.resource.str+" is not defined", null)
		
		var runs=uexp_fu.runs
		switch(runs){
			UExpParameterInt: 			if (runs.int12>measurementSimulationRuns(measurements))		error ("The utility queries runs with too high numbers",null)
			UExpParameterTrueIntRange:  if (runs.int2>measurementSimulationRuns(measurements))		error ("The utility queries runs with too high numbers",null)
		}

	}
	
	def serviceStringInServiceList (String service, List<Service> services){
		for (s:services)
			if (s.name==service)
				return true
		return false
	}
	
	def resourceStringInServiceList (String resource, List<Service> services){
		for (s:services)
			if (s.resource_id==resource)
				return true
		return false		
	}
	
	def measurementSimulationRuns(List<Measurement> measurements){
		for(m:measurements)
			switch(m){ MeasurementSimulation: return m.num_runs }
		return -1
	}

	def measurementSimulationRequests(List<Measurement> measurements){
		for(m:measurements)
			switch(m){ MeasurementSimulation: return m.num_activityis }
		return -1
	}
	
	def measurementSimulationInMeasurements(List<Measurement> measurements){
		for(m:measurements)
			switch(m){ MeasurementSimulation: return true }
		return false
	}
	
	def measurementTheoBoundsInMeasurements(List<Measurement> measurements){
		for(m:measurements)
			switch(m){ MeasurementTheoBounds: return true }
		return false		
	}
	
	@Check
	def rangeIsIncremental(UExpParameterTrueIntRange true_int_range){
		switch (true_int_range){
			UExpParameterInt:	return
			default: 			if (true_int_range.int1>=true_int_range.int2) 	error("Second value of the dotted range needs to be greater than the first", null)
		}
	}
	
	// ******************************* BOOLEAN EXPRESSION: validate whether the used dspaces all exist **********************************************************
	def List<String> boolExpUsesDspace (BExp b){
		var ret = new ArrayList<String>
		switch(b){
			BExpTrue:  			return ret
			BExpFalse: 			return ret
			BExpCmpString:		{ret.addAll(boolExpUsesDspace(b.bexpds_left.head))
								 ret.addAll(boolExpUsesDspace(b.bexpds_right.head))
								 return ret}
			BExpBi:				{ret.addAll(boolExpUsesDspace(b.bexp_left.head))
								 ret.addAll(boolExpUsesDspace(b.bexp_right.head))
								 return ret}
			BExpNeg:			return (boolExpUsesDspace(b.bexp.head)) 
			//BExpFile:			throw new Throwable("boolExpUsesDspace: Validation for file not implemented yet")
			default: 			throw new Throwable("boolExpUsesDspace: Something not implemented yet")
		}
	}

	def List<String> boolExpUsesDspace (BExpValue b){
		var ret = new ArrayList<String>	
		switch(b){
			BExpString:			return ret
			BExpDspace:			{ret.add(b.param.head)
								 return ret}
			BExpArithmetic:		{ ret.addAll(boolExpUsesDspace(b.bval_left.head))
								  ret.addAll(boolExpUsesDspace(b.bval_right.head))
								  return ret }
		}
	}
	
	@Check 
	def schedulingPolicyDefinedForValidResource (Model model) {
		var resources = model.eAllContents.toIterable.filter(typeof(AtomicResourceTree)).toList
		var mappings  = model.eAllContents.toIterable.filter(typeof(Mapping)).toList
		for(mapping:mappings)
			schedulingPolicyDefinedForValidResource(mapping, resources.map[i | i.name ])
	}
	
	def schedulingPolicyDefinedForValidResource (Mapping mapping, List<String> resources){
		for(pol:mapping.rspolicy){
			if (!resources.contains(pol.resource.toString))
				error("Resource "+pol.resource.toString+" is used in the policy but not defined in the resource section.", null)
		}
	}
	
	@Check
	def useOfValidDspacesInboolExp (Model model){
		var bexpconstraints = model.eAllContents.toIterable.filter(typeof(BExpconstraint)).toList 
		var dsms = model.eAllContents.toIterable.filter(typeof(DesignSpaceModel)).toList
		
		for(dsm:dsms)
			for(bexpconstraint:bexpconstraints){
				var List<String> dsm_params 	= params_of_DSM(dsm)
				var List<String> bexp_params	= boolExpUsesDspace(bexpconstraint.bexp.head)
				System.out.println(dsm_params)
				System.out.println(bexp_params)
				
				for(bexp_param:bexp_params)
					if (!dsm_params.contains(bexp_param) && bexp_param!="sampling_method") 
						warning2("Boolean constraints rely on "+bexp_param+", which the design space does not contain",null)
			} 	
	}
	
	@Check
	def atomsInLBAltHaveSimilarLoadExp (LoadBalancerProcessModel lbpmodel){ // see if all taskloads in a Loadbalancer are similar
		var Exp fstTaskload = lbpmodel.pmodel.head.taskload.head.load // compare all other taskloads with the first one
		for(apmodel:lbpmodel.pmodel){
			var Exp cmpTaskload = apmodel.taskload.head.load
			if(!compare_exp(fstTaskload, cmpTaskload))
				error("Not all taskloads in the Loadbalancer are the same!", null)
		}
		// warn for the above no matter what
		warning2("All taskloads in a Loadbalancer should be the same",null)
	}
	
	def boolean compare_exp (Exp tl1, Exp tl2){
		return true // TODO compare two EXPs		
	}
}